import { z } from "zod";
import { backendFetch } from "../../utils/backend";

/**
 * Shape of the data object returned by POST /api/chat/query on the NestJS backend.
 * Exported so the client composable can import it for static typing without duplicating
 * the contract. `rows` uses the widest safe SQL cell type; SQL NULLs arrive as null.
 */
export interface ChatQueryResult {
  /** Natural-language answer synthesised from the query results. */
  answer: string;
  /** The SQL statement generated by the LLM and executed against the tenant DB. */
  sql: string;
  /** Column names in declaration order (empty when the query returns no rows). */
  columns: string[];
  /** Result rows. Each cell is a string, number, or null (SQL NULL). */
  rows: (string | number | null)[][];
  /** AI provider identifier (e.g. "mock", "openai"). */
  provider: string;
  /** Model identifier within the provider (e.g. "gpt-4o-mini"). */
  model: string;
}

interface Envelope<T> {
  success: boolean;
  data: T;
}

// Validates the request body: question must be a non-empty string up to 2 000 chars.
// The backend enforces the same constraint; the BFF adds a first line of defence.
const queryBodySchema = z.object({
  question: z
    .string()
    .min(1, "La pregunta no puede estar vacía")
    .max(2000, "La pregunta no puede superar los 2000 caracteres"),
});

/**
 * BFF proxy for E09 Chat IA.
 *
 * POST /api/chat/query → POST http://backend/api/chat/query
 *
 * Auth: session cookie (Bearer forwarded by `backendFetch`). The NestJS backend
 * enforces CASL: owner/manager only — staff receives 403 which propagates as-is.
 * 400 from the backend (unsafe/unresolvable query) is also propagated; the client
 * composable renders it as a friendly assistant message rather than a crash.
 */
export default defineEventHandler(async (event) => {
  const body = await readValidatedBody(event, queryBodySchema.parse);
  const res = await backendFetch<Envelope<ChatQueryResult>>(
    event,
    "/api/chat/query",
    {
      method: "POST",
      body,
    },
  );
  return ok(res.data);
});
