import { z } from "zod";
import type {
  ChatForecastMeta,
  ChatForecastPoint,
  ChatQueryKind,
} from "#shared/types/domain";
import { backendFetch } from "../../utils/backend";
import {
  toDriver,
  type BeForecastDriver,
} from "../../utils/forecasting-adapter";

/**
 * Raw `forecast.points[]` entry as emitted by the backend (core-ai contract,
 * snake_case — see `forecastPointSchema` in `src/shared/forecasting/forecast.ts`
 * on team-backend).
 */
interface BeChatForecastPoint {
  target_date: string;
  yhat: number;
  yhat_lo: number;
  yhat_hi: number;
}

/**
 * Raw `forecast` block as emitted by the backend (F2b / LOTE B3 — see
 * `chatForecastMetaSchema` in `src/shared/chat/chat.ts` on team-backend).
 * Top-level keys are already camelCase; only the nested `points`/`drivers`
 * inherit core-ai's snake_case field names, so those need mapping.
 */
interface BeChatForecastMeta {
  runId: string;
  range: { from: string; to: string; label: string };
  totalYhat: number;
  totalLo: number;
  totalHi: number;
  points: BeChatForecastPoint[];
  drivers: BeForecastDriver[];
}

/** Raw shape of the data object returned by POST /api/chat/query on the NestJS backend. */
interface BeChatQueryResult {
  answer: string;
  sql: string;
  columns: string[];
  rows: (string | number | null)[][];
  provider: string;
  model: string;
  /** ADDITIVE (F2b) — absent on responses from before this batch shipped. */
  kind?: ChatQueryKind;
  /** ADDITIVE (F2b) — present only when `kind === 'future'` and data was available. */
  forecast?: BeChatForecastMeta;
}

/**
 * Shape of the data object this BFF route returns to the client (post-mapping).
 * Exported so the client composable can import it for static typing without
 * duplicating the contract. `rows` uses the widest safe SQL cell type; SQL
 * NULLs arrive as null. `kind`/`forecast` are ADDITIVE (F2b) — a client that
 * still only reads `answer/sql/columns/rows/provider/model` keeps working.
 */
export interface ChatQueryResult {
  /** Natural-language answer synthesised from the query results. */
  answer: string;
  /** The SQL statement generated by the LLM and executed against the tenant DB. */
  sql: string;
  /** Column names in declaration order (empty when the query returns no rows). */
  columns: string[];
  /** Result rows. Each cell is a string, number, or null (SQL NULL). */
  rows: (string | number | null)[][];
  /** AI provider identifier (e.g. "mock", "openai"), or "system" for non-LLM responses. */
  provider: string;
  /** Model identifier within the provider (e.g. "gpt-4o-mini", or "forecast-run"/"intent-classifier"). */
  model: string;
  /** Question classification (F2b). Absent on legacy responses — treat as `historical`. */
  kind?: ChatQueryKind;
  /** Structured forecast data (F2b), mapped to camelCase; present only for `kind: 'future'` with data. */
  forecast?: ChatForecastMeta;
}

interface Envelope<T> {
  success: boolean;
  data: T;
}

/** Maps a raw backend forecast point (snake_case) to the frontend's camelCase view. */
function toForecastPoint(p: BeChatForecastPoint): ChatForecastPoint {
  return {
    targetDate: p.target_date,
    yhat: p.yhat,
    yhatLo: p.yhat_lo,
    yhatHi: p.yhat_hi,
  };
}

/** Maps the raw backend `forecast` block to the frontend's camelCase view. */
function toForecastMeta(f: BeChatForecastMeta): ChatForecastMeta {
  return {
    runId: f.runId,
    range: f.range,
    totalYhat: f.totalYhat,
    totalLo: f.totalLo,
    totalHi: f.totalHi,
    points: f.points.map(toForecastPoint),
    drivers: f.drivers.map(toDriver),
  };
}

/** Maps the raw backend chat response to the shape this BFF route returns. */
function toChatQueryResult(be: BeChatQueryResult): ChatQueryResult {
  return {
    answer: be.answer,
    sql: be.sql,
    columns: be.columns,
    rows: be.rows,
    provider: be.provider,
    model: be.model,
    kind: be.kind,
    forecast: be.forecast ? toForecastMeta(be.forecast) : undefined,
  };
}

// Validates the request body: question must be a non-empty string up to 2 000 chars.
// The backend enforces the same constraint; the BFF adds a first line of defence.
const queryBodySchema = z.object({
  question: z
    .string()
    .min(1, "La pregunta no puede estar vacía")
    .max(2000, "La pregunta no puede superar los 2000 caracteres"),
});

/**
 * BFF proxy for E09 Chat IA.
 *
 * POST /api/chat/query → POST http://backend/api/chat/query
 *
 * Auth: session cookie (Bearer forwarded by `backendFetch`). The NestJS backend
 * enforces CASL: owner/manager only — staff receives 403 which propagates as-is.
 * 400 from the backend (unsafe/unresolvable query) is also propagated; the client
 * composable renders it as a friendly assistant message rather than a crash.
 */
export default defineEventHandler(async (event) => {
  const body = await readValidatedBody(event, queryBodySchema.parse);
  const res = await backendFetch<Envelope<BeChatQueryResult>>(
    event,
    "/api/chat/query",
    {
      method: "POST",
      body,
    },
  );
  return ok(toChatQueryResult(res.data));
});
